package com.startfive.app.notifications

internal object NotificationContract {
  const val MODULE_NAME = "StartFiveNotifications"
  const val TAP_EVENT = "startFiveNotificationTap"
  const val CHANNEL_ID = "start_five_reminders"
  const val CHANNEL_NAME = "任务提醒"
  const val FOCUS_CHANNEL_ID = "start_five_focus"
  const val FOCUS_CHANNEL_NAME = "正在专注"
  const val FOCUS_QUIET_PREFERENCES = "start_five_focus_quiet_v1"
  const val FOCUS_QUIET_SESSION_KEY = "session_id"
  const val FOCUS_QUIET_UNTIL_KEY = "quiet_until_epoch_ms"
  const val ACTION_ALARM = "com.startfive.app.NOTIFICATION_ALARM"
  const val ACTION_TAP = "com.startfive.app.NOTIFICATION_TAP"
  const val ACTION_SHORTCUT_ADD = "com.startfive.app.SHORTCUT_ADD"
  const val ACTION_SHORTCUT_CONTINUE = "com.startfive.app.SHORTCUT_CONTINUE"
  const val ACTION_SHORTCUT_START_FIVE = "com.startfive.app.SHORTCUT_START_FIVE"
  const val EXTRA_STABLE_ID = "start_five_stable_id"
  const val EXTRA_TASK_ID = "start_five_task_id"
  const val EXTRA_RULE_ID = "start_five_rule_id"
  const val EXTRA_REMINDER_KIND = "start_five_reminder_kind"
  const val EXTRA_NOTIFICATION_TITLE = "start_five_notification_title"
  const val EXTRA_NOTIFICATION_BODY = "start_five_notification_body"
  const val EXTRA_TAP_KIND = "start_five_tap_kind"
  const val EXTRA_DAY_KEY = "start_five_day_key"
  const val EXTRA_SCHEDULE_ID = "start_five_schedule_id"
  const val EXTRA_SESSION_ID = "start_five_session_id"
  const val EXTRA_ENTRY_ID = "start_five_entry_id"
  const val TAP_KIND_TOMORROW_FIRST = "tomorrow_first"
  const val TAP_KIND_START_FIVE = "start_five"
  const val TAP_KIND_DELAY_TEN = "delay_ten"
  const val TAP_KIND_RESCHEDULE = "reschedule"
  const val TAP_KIND_FOCUS_SCHEDULE_START_FIVE = "focus_schedule_start_five"
  const val TAP_KIND_FOCUS_SCHEDULE_START_PLANNED = "focus_schedule_start_planned"
  const val TAP_KIND_FOCUS_SCHEDULE_DELAY_TEN = "focus_schedule_delay_ten"
  const val TAP_KIND_FOCUS_SCHEDULE_SKIP = "focus_schedule_skip"
  const val TAP_KIND_FOCUS_SCHEDULE_OPEN = "focus_schedule_open"
  const val TAP_KIND_FOCUS_ONGOING_CONTINUE = "focus_ongoing_continue"
  const val TAP_KIND_FOCUS_ONGOING_END = "focus_ongoing_end"
  const val TAP_KIND_SHORTCUT_ADD = "shortcut_add"
  const val TAP_KIND_SHORTCUT_CONTINUE = "shortcut_continue"
  const val TAP_KIND_SHORTCUT_START_FIVE = "shortcut_start_five"
  const val TAP_KIND_SHARE_TEXT = "share_text"
  const val MAX_SHARED_TEXT_LENGTH = 500
}
